Get the initial table of case studies with the centre coordinate for a buffer area.

Not a part of reproducible code, will not be published.

In [2]:
import geopandas as gpd
import pandas as pd
import glob
import pathlib

In [3]:
files = glob.glob("../../Dropbox/Academia/Data/Geo/Resilience/data_resilience_e_ais/*/*/data.gpkg")

In [23]:
cases = pd.DataFrame(columns=["period", "origin"])

for f in files:
    path = pathlib.Path(f)
    buffer = gpd.read_file(f, layer='buffer400').to_crs(4326)
    point = list(buffer.geometry.iloc[0].centroid.coords)[0]
    cases.loc[path.parent.name] = [path.parent.parent.name, point]

/opt/conda/lib/python3.8/site-packages/geopandas/geodataframe.py:422: RuntimeWarning: Sequential read of iterator was interrupted. Resetting iterator. This can negatively impact the performance.
  for feature in features_lst:

In [28]:
cases

,case,period,origin
0,Athens,1_pre-Industrial,"(23.729297894645065, 37.977742321097296)"
1,Brugge,1_pre-Industrial,"(3.222135599564842, 51.20663413385126)"
2,Havana,1_pre-Industrial,"(-82.35387869733259, 23.137058811383366)"
3,Kyoto,1_pre-Industrial,"(135.77513789847612, 35.00441991880096)"
4,Nuremberg,1_pre-Industrial,"(11.080741895925831, 49.4558122318182)"
5,Pavia,1_pre-Industrial,"(9.155202505665285, 45.18542787308676)"
6,Recife,1_pre-Industrial,"(-34.87950134898907, -8.066819977715335)"
7,Barcelona,2_industrial,"(2.1599658311051333, 41.39207228345335)"
8,Brisbane,2_industrial,"(153.00890689998246, -27.483072513877765)"
9,Buenos_aires,2_industrial,"(-58.37436109734774, -34.618526518125655)"
10,Chicago,2_industrial,"(-87.6496541987247, 41.91601382423912)"
11,Gresham,2_industrial,"(-1.247420873587431, 54.56718112225616)"
12,Paris,2_industrial,"(2.3036982060349636, 48.86864235146261)"
13,Philadelphia,2_industrial,"(-75.17713599972483, 39.92784202217783)"
14,Akademgorodok,3_Modernist,"(83.10742859587872, 54.83929583879922)"
15,Brasilia,3_Modernist,"(-47.91657209425542, -15.823763507567802)"
16,Drumul Taberei,3_Modernist,"(26.02122171749766, 44.41721907853648)"
17,Kilamba,3_Modernist,"(13.273496897999385, -8.998426816984628)"
18,Marzhan,3_Modernist,"(13.558283202822224, 52.55398573559633)"
19,Tblisi,3_Modernist,"(44.72275760065603, 41.72302532410621)"
20,Washington,3_Modernist,"(-77.01384344364777, 38.87647174832982)"
21,Ciudad_Guayana,4_Garden_city,"(-62.67209868783639, 8.34826427219966)"
22,Frohnau,4_Garden_city,"(13.277062904022877, 52.631536235815815)"
23,Hilversum,4_Garden_city,"(5.170650196333054, 52.23187803549469)"
24,Montreal,4_Garden_city,"(-73.64192800272671, 45.522340227287295)"
25,Shenley_lodge,4_Garden_city,"(-0.7764592316902924, 52.01824459511488)"
26,Stratton,4_Garden_city,"(116.04114530164892, -31.864639316563675)"
27,Tel_Aviv,4_Garden_city,"(34.977140396112986, 32.0925043168361)"
28,Auckland,5_Neo-traditional,"(174.9160552559242, -36.95408615897924)"
29,Brandevoort,5_Neo-traditional,"(5.62261399486988, 51.46170483425585)"
30,Cornell_village,5_Neo-traditional,"(-79.23037000333382, 43.88964002638408)"
31,Kentlands,5_Neo-traditional,"(-77.24424129756238, 39.120324272641994)"
32,Mueller,5_Neo-traditional,"(-97.70314980255172, 30.292836815637383)"
33,Poundbury,5_Neo-traditional,"(-2.4659421804937587, 50.712394108768116)"
34,Rieselfield,5_Neo-traditional,"(7.792109457726385, 47.99888843253804)"
35,Abdurahmangazi,6_Informal,"(29.25333679557981, 40.96419132348267)"
36,Bicentennaire,6_Informal,"(-72.35389200521153, 18.535389208950473)"
37,Jardim_Portal_I,6_Informal,"(-46.57587250888991, -23.440949292392443)"
38,Khayeltisha,6_Informal,"(18.655964304683074, -34.02152631858855)"
39,Kricak,6_Informal,"(110.35677760126997, -7.773518503607216)"
40,Mafalala,6_Informal,"(32.572846900841455, -25.952561712972226)"
41,Tandale,6_Informal,"(39.24312098621779, -6.792734470840269)"
42,Tondo,6_Informal,"(120.9641471044341, 14.616058307179102)"

In [25]:
cases = cases.reset_index()

In [27]:
cases = cases.rename(columns={"index": "case"})

In [29]:
cases = cases.replace({"1_pre-Industrial": "pre-industrial", "2_industrial": "industrial", "3_Modernist": "modernist", "4_Garden_city": "garden city", 
                      "5_Neo-traditional": "neo-traditional", "6_Informal": "informal"})

In [30]:
cases

,case,period,origin
0,Athens,pre-industrial,"(23.729297894645065, 37.977742321097296)"
1,Brugge,pre-industrial,"(3.222135599564842, 51.20663413385126)"
2,Havana,pre-industrial,"(-82.35387869733259, 23.137058811383366)"
3,Kyoto,pre-industrial,"(135.77513789847612, 35.00441991880096)"
4,Nuremberg,pre-industrial,"(11.080741895925831, 49.4558122318182)"
5,Pavia,pre-industrial,"(9.155202505665285, 45.18542787308676)"
6,Recife,pre-industrial,"(-34.87950134898907, -8.066819977715335)"
7,Barcelona,industrial,"(2.1599658311051333, 41.39207228345335)"
8,Brisbane,industrial,"(153.00890689998246, -27.483072513877765)"
9,Buenos_aires,industrial,"(-58.37436109734774, -34.618526518125655)"
10,Chicago,industrial,"(-87.6496541987247, 41.91601382423912)"
11,Gresham,industrial,"(-1.247420873587431, 54.56718112225616)"
12,Paris,industrial,"(2.3036982060349636, 48.86864235146261)"
13,Philadelphia,industrial,"(-75.17713599972483, 39.92784202217783)"
14,Akademgorodok,modernist,"(83.10742859587872, 54.83929583879922)"
15,Brasilia,modernist,"(-47.91657209425542, -15.823763507567802)"
16,Drumul Taberei,modernist,"(26.02122171749766, 44.41721907853648)"
17,Kilamba,modernist,"(13.273496897999385, -8.998426816984628)"
18,Marzhan,modernist,"(13.558283202822224, 52.55398573559633)"
19,Tblisi,modernist,"(44.72275760065603, 41.72302532410621)"
20,Washington,modernist,"(-77.01384344364777, 38.87647174832982)"
21,Ciudad_Guayana,garden city,"(-62.67209868783639, 8.34826427219966)"
22,Frohnau,garden city,"(13.277062904022877, 52.631536235815815)"
23,Hilversum,garden city,"(5.170650196333054, 52.23187803549469)"
24,Montreal,garden city,"(-73.64192800272671, 45.522340227287295)"
25,Shenley_lodge,garden city,"(-0.7764592316902924, 52.01824459511488)"
26,Stratton,garden city,"(116.04114530164892, -31.864639316563675)"
27,Tel_Aviv,garden city,"(34.977140396112986, 32.0925043168361)"
28,Auckland,neo-traditional,"(174.9160552559242, -36.95408615897924)"
29,Brandevoort,neo-traditional,"(5.62261399486988, 51.46170483425585)"
30,Cornell_village,neo-traditional,"(-79.23037000333382, 43.88964002638408)"
31,Kentlands,neo-traditional,"(-77.24424129756238, 39.120324272641994)"
32,Mueller,neo-traditional,"(-97.70314980255172, 30.292836815637383)"
33,Poundbury,neo-traditional,"(-2.4659421804937587, 50.712394108768116)"
34,Rieselfield,neo-traditional,"(7.792109457726385, 47.99888843253804)"
35,Abdurahmangazi,informal,"(29.25333679557981, 40.96419132348267)"
36,Bicentennaire,informal,"(-72.35389200521153, 18.535389208950473)"
37,Jardim_Portal_I,informal,"(-46.57587250888991, -23.440949292392443)"
38,Khayeltisha,informal,"(18.655964304683074, -34.02152631858855)"
39,Kricak,informal,"(110.35677760126997, -7.773518503607216)"
40,Mafalala,informal,"(32.572846900841455, -25.952561712972226)"
41,Tandale,informal,"(39.24312098621779, -6.792734470840269)"
42,Tondo,informal,"(120.9641471044341, 14.616058307179102)"

In [31]:
cases = cases.replace({"Buenos_aires": "Buenos Aires", "Ciudad_Guayana": "Ciudad Guayana", "Shenley_lodge": "Shenley Lodge", "Tel_Aviv": "Tel Aviv",
                      "Cornell_village": "Cornell Village", "Jardim_Portal_I": "Jardim Portal I e II"})

In [32]:
cases

,case,period,origin
0,Athens,pre-industrial,"(23.729297894645065, 37.977742321097296)"
1,Brugge,pre-industrial,"(3.222135599564842, 51.20663413385126)"
2,Havana,pre-industrial,"(-82.35387869733259, 23.137058811383366)"
3,Kyoto,pre-industrial,"(135.77513789847612, 35.00441991880096)"
4,Nuremberg,pre-industrial,"(11.080741895925831, 49.4558122318182)"
5,Pavia,pre-industrial,"(9.155202505665285, 45.18542787308676)"
6,Recife,pre-industrial,"(-34.87950134898907, -8.066819977715335)"
7,Barcelona,industrial,"(2.1599658311051333, 41.39207228345335)"
8,Brisbane,industrial,"(153.00890689998246, -27.483072513877765)"
9,Buenos Aires,industrial,"(-58.37436109734774, -34.618526518125655)"
10,Chicago,industrial,"(-87.6496541987247, 41.91601382423912)"
11,Gresham,industrial,"(-1.247420873587431, 54.56718112225616)"
12,Paris,industrial,"(2.3036982060349636, 48.86864235146261)"
13,Philadelphia,industrial,"(-75.17713599972483, 39.92784202217783)"
14,Akademgorodok,modernist,"(83.10742859587872, 54.83929583879922)"
15,Brasilia,modernist,"(-47.91657209425542, -15.823763507567802)"
16,Drumul Taberei,modernist,"(26.02122171749766, 44.41721907853648)"
17,Kilamba,modernist,"(13.273496897999385, -8.998426816984628)"
18,Marzhan,modernist,"(13.558283202822224, 52.55398573559633)"
19,Tblisi,modernist,"(44.72275760065603, 41.72302532410621)"
20,Washington,modernist,"(-77.01384344364777, 38.87647174832982)"
21,Ciudad Guayana,garden city,"(-62.67209868783639, 8.34826427219966)"
22,Frohnau,garden city,"(13.277062904022877, 52.631536235815815)"
23,Hilversum,garden city,"(5.170650196333054, 52.23187803549469)"
24,Montreal,garden city,"(-73.64192800272671, 45.522340227287295)"
25,Shenley Lodge,garden city,"(-0.7764592316902924, 52.01824459511488)"
26,Stratton,garden city,"(116.04114530164892, -31.864639316563675)"
27,Tel Aviv,garden city,"(34.977140396112986, 32.0925043168361)"
28,Auckland,neo-traditional,"(174.9160552559242, -36.95408615897924)"
29,Brandevoort,neo-traditional,"(5.62261399486988, 51.46170483425585)"
30,Cornell Village,neo-traditional,"(-79.23037000333382, 43.88964002638408)"
31,Kentlands,neo-traditional,"(-77.24424129756238, 39.120324272641994)"
32,Mueller,neo-traditional,"(-97.70314980255172, 30.292836815637383)"
33,Poundbury,neo-traditional,"(-2.4659421804937587, 50.712394108768116)"
34,Rieselfield,neo-traditional,"(7.792109457726385, 47.99888843253804)"
35,Abdurahmangazi,informal,"(29.25333679557981, 40.96419132348267)"
36,Bicentennaire,informal,"(-72.35389200521153, 18.535389208950473)"
37,Jardim Portal I e II,informal,"(-46.57587250888991, -23.440949292392443)"
38,Khayeltisha,informal,"(18.655964304683074, -34.02152631858855)"
39,Kricak,informal,"(110.35677760126997, -7.773518503607216)"
40,Mafalala,informal,"(32.572846900841455, -25.952561712972226)"
41,Tandale,informal,"(39.24312098621779, -6.792734470840269)"
42,Tondo,informal,"(120.9641471044341, 14.616058307179102)"

In [36]:
cases.loc[25] = ["Greenhills", "garden city", (-87.996019, 42.941374)]

/opt/conda/lib/python3.8/site-packages/pandas/core/internals/blocks.py:983: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr_value = np.array(value)

In [40]:
cases.loc[20] = ["Karvina", "modernist", (18.557418, 49.853861)]

In [41]:
cases.loc[11] = ["De Pijp", "industrial", (4.890787, 52.353532)]

In [44]:
cases.loc[33] = ["Miami Lakes", "neo-traditional", (-80.311950, 25.905058)]

/opt/conda/lib/python3.8/site-packages/pandas/core/internals/blocks.py:983: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr_value = np.array(value)

In [46]:
cases.to_csv("data/case_studies.csv", index=False)

In [45]:
cases

,case,period,origin
0,Athens,pre-industrial,"(23.729297894645065, 37.977742321097296)"
1,Brugge,pre-industrial,"(3.222135599564842, 51.20663413385126)"
2,Havana,pre-industrial,"(-82.35387869733259, 23.137058811383366)"
3,Kyoto,pre-industrial,"(135.77513789847612, 35.00441991880096)"
4,Nuremberg,pre-industrial,"(11.080741895925831, 49.4558122318182)"
5,Pavia,pre-industrial,"(9.155202505665285, 45.18542787308676)"
6,Recife,pre-industrial,"(-34.87950134898907, -8.066819977715335)"
7,Barcelona,industrial,"(2.1599658311051333, 41.39207228345335)"
8,Brisbane,industrial,"(153.00890689998246, -27.483072513877765)"
9,Buenos Aires,industrial,"(-58.37436109734774, -34.618526518125655)"
10,Chicago,industrial,"(-87.6496541987247, 41.91601382423912)"
11,De Pijp,industrial,"(4.890787, 52.353532)"
12,Paris,industrial,"(2.3036982060349636, 48.86864235146261)"
13,Philadelphia,industrial,"(-75.17713599972483, 39.92784202217783)"
14,Akademgorodok,modernist,"(83.10742859587872, 54.83929583879922)"
15,Brasilia,modernist,"(-47.91657209425542, -15.823763507567802)"
16,Drumul Taberei,modernist,"(26.02122171749766, 44.41721907853648)"
17,Kilamba,modernist,"(13.273496897999385, -8.998426816984628)"
18,Marzhan,modernist,"(13.558283202822224, 52.55398573559633)"
19,Tblisi,modernist,"(44.72275760065603, 41.72302532410621)"
20,Karvina,modernist,"(18.557418, 49.853861)"
21,Ciudad Guayana,garden city,"(-62.67209868783639, 8.34826427219966)"
22,Frohnau,garden city,"(13.277062904022877, 52.631536235815815)"
23,Hilversum,garden city,"(5.170650196333054, 52.23187803549469)"
24,Montreal,garden city,"(-73.64192800272671, 45.522340227287295)"
25,Greenhills,garden city,"(-87.996019, 42.941374)"
26,Stratton,garden city,"(116.04114530164892, -31.864639316563675)"
27,Tel Aviv,garden city,"(34.977140396112986, 32.0925043168361)"
28,Auckland,neo-traditional,"(174.9160552559242, -36.95408615897924)"
29,Brandevoort,neo-traditional,"(5.62261399486988, 51.46170483425585)"
30,Cornell Village,neo-traditional,"(-79.23037000333382, 43.88964002638408)"
31,Kentlands,neo-traditional,"(-77.24424129756238, 39.120324272641994)"
32,Mueller,neo-traditional,"(-97.70314980255172, 30.292836815637383)"
33,Miami Lakes,neo-traditional,"(-80.31195, 25.905058)"
34,Rieselfield,neo-traditional,"(7.792109457726385, 47.99888843253804)"
35,Abdurahmangazi,informal,"(29.25333679557981, 40.96419132348267)"
36,Bicentennaire,informal,"(-72.35389200521153, 18.535389208950473)"
37,Jardim Portal I e II,informal,"(-46.57587250888991, -23.440949292392443)"
38,Khayeltisha,informal,"(18.655964304683074, -34.02152631858855)"
39,Kricak,informal,"(110.35677760126997, -7.773518503607216)"
40,Mafalala,informal,"(32.572846900841455, -25.952561712972226)"
41,Tandale,informal,"(39.24312098621779, -6.792734470840269)"
42,Tondo,informal,"(120.9641471044341, 14.616058307179102)"